# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
pan1:
  ID: 11
 # Protocol_Version: 1
  Return_Delay_Time: 0
  
    
pan2:
 # Protocol_Version: 1
  ID: 12
  Return_Delay_Time: 0
  

pan3:
  ID: 13
 # Protocol_Version: 1
  Return_Delay_Time: 0
  
    
pan4:
  # Protocol_Version: 1
  ID: 21
  Return_Delay_Time: 0

pan5:
  ID: 22
 # Protocol_Version: 1
  Return_Delay_Time: 0
  
    
pan6:
 # Protocol_Version: 1
  ID: 23
  Return_Delay_Time: 0
  
pan7:
  ID: 31
 # Protocol_Version: 1
  Return_Delay_Time: 0
  
    
pan8:
 # Protocol_Version: 1
  ID: 32
  Return_Delay_Time: 0
  
pan9:
  ID: 33
 # Protocol_Version: 1
  Return_Delay_Time: 0
  
    
pan10:
 # Protocol_Version: 1
  ID: 41
  Return_Delay_Time: 0
  
pan11:
  ID: 42
 # Protocol_Version: 1
  Return_Delay_Time: 0
  
    
pan12:
 # Protocol_Version: 1
  ID: 43
  Return_Delay_Time: 0
  
