controller_joint_names: ['', 'L1_joint_1', 'L1_joint_2', 'L1_joint_3', 'L2_joint_1', 'L2_joint_2', 'L2_joint_3', 'L3_joint_1', 'L3_joint_2', 'L3_joint_3', 'L4_joint_1', 'L4_joint_2', 'L4_joint_3', ]
